language: node_js
node_js:
  - 6

sudo: false

env:
  global:
    - secure: "k1+Jxz/W2+H+OH+63CnOcDC98I5vZ3KDXogAkYbu4uoNaEfGdH6EumuvXzeI9LuA9mHDuUUe2/4W1a6Xs2qQbZ3DLZg2Hm/pnzfn4/n3SMp+SXwGIom7pbkUOUA2g9EJ5jkNxVENgU9EMkxa8IMHKyc+NlLdTbVScXAGskdBxfs0/aSIPpb38JowYJgIBlui3mQoEFEr6x1Pp/dynt6ZIvDBNZLqct1Fp8Q/z9FQewkKwMjEwzFYJ0BPYt2eIp9frpO1dWTiNRZXIJVwh3z1dysN4x71744AYWoFIb0+hIl5ebSrwReUg0nxJ4OKkqIeTkO+6mxnd+x/U2Ga6CYUeIjQSpmNGr3RQK/3PvnJZiBbAdziwMv9kV8FG4h5cayTqi4ZDGQEUHiNDOJhyHxSORkdUv7iRROZeDcp1S6R5vcMfFo+0GLgKoAJyrSPBbE+Zaudn+wFwaTq4yqfeqWEMMJzCaMXM9mZFMqKVMUX6ytjh4jw5PcBzYkghytR19e3I9SRdQ2vSXX0/waGOhDc0FFkxt+2PpFZGCX5RRcU3nH48WJnHiwrblRyh3rlQIZx6ewN1I9s7/UgSmiLnZ2nIUNYoy+DjLU+JSZgyWHVjw54koP6AO92Ol+5tSwwal6jvE98P0Q0gMI8FjziyviqsCuf0teWWBB9p7u5iujIi74=" # CF_DEPLOY_USER
    - secure: "jCRqWU057ewUhS7a+ZjTE18jlPdfNyXMl461DZ5aeNORF/DsESS7Ym8npYG90VzGTImQfasO1/dwcMvXwc1UYl9Fn2NDpGOlMNr/C3Li6gCr/QOIwIBbHuJ2k21NbFKCAaGwJMIcjF9S9rl6n+DznqNp60jwOQhawOo80l45yh8RLJrWDiBzBs3qFY5cJbSghv2fxv5HIXyr/Ezx2vorI/ZfB3rsacsg0gp6dO7Yzirk7H2KuzL6I8s5oIFk1vRFAFS/PC8GmikOqNkVzgju627+glXE/3hlphIu1lI8mQjW/JXWEISxcK7hyySzEhduDTEaH2sIO+qNGOMSyAx6xO9OFlhFkb31DfesXSEXTnFA1FST11xCH5yYZgp+ZARG7Q5Dqyw2iWpTeXc+KoD647EXLr+ktJHYJcGQdeVyP0BB3T+1Ywv1obeSZNwCTVf5tY2MoOT/0a1C4xHU6v7DShmfuk6VT1AqH/Kt3YatCF07hg42iGZO/XGtzHoRSTH7NjulQabfyW7Koni0ovoaosD/SkmiUlS3Zn+lp0mqabEy33ekkdv0cP3oQtwK3xwYP5nl2R+VaYUDWdUGicZJfaZrM6KgGl+bDmwW7P6q/mob5bG/PedOuP97K/CM38Pb7aIC4vnzRLfGVqFud7dxXbkg99cN2UzBsy+7ynBnTIA=" # CF_DEPLOY_PASSWORD

before_deploy:
  - npm run build
  - mkdir -p $HOME/bin
  - export PATH=$HOME/bin:$PATH
  - travis_retry curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.23.0" | tar xzv -C $HOME/bin
  - travis_retry cf install-plugin autopilot -f -r CF-Community

deploy:
  - provider: script
    skip_cleanup: true
    script: ./bin/cf_deploy.sh fec-pattern-library fec-beta-fec dev
    on:
      branch: master
