# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
jobs:
  build-and-deploy-job:
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - fec-pattern-library-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - fec-pattern-library-dependencies-

      - run:
          name: Install node dependencies
          command: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
            echo ". ~/.nvm/nvm.sh" >> $BASH_ENV
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
            nvm install 8.9.1
            nvm use 8.9.1
            nvm alias default 8.9.1
            npm install -g @frctl/fractal
            npm install
            npm run build

      - run:
          name: Install cf cli
          command: |
            mkdir -p $HOME/bin
            export PATH=$HOME/bin:$PATH
            curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.32.0" | tar xzv -C $HOME/bin
            cf install-plugin autopilot -f -r CF-Community

      - deploy:
          name: Deploy Pattern Library
          command: |
            export PATH=$HOME/bin:$PATH
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
            nvm use default
            ./bin/cf_deploy.sh fec-pattern-library fec-beta-fec dev

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-deploy-job:
          filters:
            branches:
              only: master
