# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
jobs:
  build-and-deploy-job:
    docker:
      - image: circleci/node:8.9.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - fec-pattern-library-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - fec-pattern-library-dependencies-

      - run:
          name: Install Node.js Dependencies
          command: |
            npm install
            npm run build

      - run:
          name: Install CF CLI
          command: |
            mkdir -p $HOME/bin
            export PATH=$HOME/bin:$PATH
            curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.33.0" | tar xzv -C $HOME/bin
            cf install-plugin autopilot -f -r CF-Community

      - deploy:
          name: Deploy Pattern Library
          command: |
            export PATH=$HOME/bin:$PATH
            ./bin/cf_deploy.sh fec-pattern-library fec-beta-fec dev

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-deploy-job:
          filters:
            branches:
              only: master
